# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Gentoo Theme"
license = "MIT"
licenselink = "https://github.com/flimberger/hugo-gentoo-theme/blob/master/LICENSE.md"
description = "This is a Hugo theme inspired by the look of the Gentoo penguin."
homepage = "https://github.com/flimberger/hugo-gentoo-theme"
tags = ["blog", "responsive"]
features = ["blog", "themes", "responsive"]
min_version = 0.19

authors = [
    {name = "Daisuke Konishi", homepage = "https://blog.daisukekonishi.com"},
    {name = "Florian Limberger", homepage = "https://machineroom.purplekraken.com"}
]

[original]
    author = "Daisuke Konishi"
    homepage = "https://github.com/d-kusk/hugo-gentoo-theme/"
    repo = "https://github.com/d-kusk/hugo-gentoo-theme/"
